// <auto-generated />
using System;
using Doceria.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Doceria.Migrations
{
    [DbContext(typeof(DoceriaContext))]
    [Migration("20220316122424_DoceriaDBStart")]
    partial class DoceriaDBStart
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Doceria.Models.Torta", b =>
                {
                    b.Property<int>("TortaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_CADASTRO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("DS_TORTA");

                    b.Property<bool>("IsVegana")
                        .HasColumnType("bit")
                        .HasColumnName("BL_VEGANA");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NM_TORTA");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VL_PRECO");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("NM_TIPO");

                    b.HasKey("TortaId");

                    b.ToTable("TB_TORTA");
                });
#pragma warning restore 612, 618
        }
    }
}
